apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.8.1-php8.1-apache
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: wordpress-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            cpu: "1200m"
            memory: "1Gi"
        volumeMounts:
        - name: wp-data-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-data-storage
        persistentVolumeClaim:
          claimName: wp-data-pvc